#!/usr/bin/env python3
"""Validate suite and Cloud BMT backend layout policy."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from tools.bmt.project_sources import discover_project_sources, examples_source_dir, load_project_manifest
from tools.repo.paths import DEFAULT_CONFIG_ROOT, DEFAULT_STAGE_ROOT, repo_root, suite_root

SUITE_ALLOWED_TOP_LEVEL = {
    ".actrc",
    ".codex",
    ".cursorignore",
    ".cursorindexingignore",
    ".dockerignore",
    ".env.example",
    ".gitattributes",
    ".github",
    ".gitignore",
    ".pre-commit-config.yaml",
    ".python-version",
    "AGENTS.md",
    "CLAUDE.md",
    "Justfile",
    "LICENSE",
    "README.md",
    "ci",
    "docs",
    "examples",
    "infra",
    "projects",
    "pyproject.toml",
    "pyrightconfig.json",
    "runtime",
    "ruff.toml",
    "scripts",
    "sdk",
    "tests",
    "tools",
    "uv.lock",
}

BACKEND_ALLOWED_TOP_LEVEL = {
    ".actrc",
    ".codex",
    ".cursorignore",
    ".cursorindexingignore",
    ".dockerignore",
    ".env.example",
    ".gitattributes",
    ".github",
    ".gitignore",
    ".pre-commit-config.yaml",
    ".python-version",
    "AGENTS.md",
    "ARCHITECTURE.md",
    "CHANGELOG.md",
    "CLAUDE.md",
    "CONTRIBUTING.md",
    "CMakePresets.json",
    "CMakeLists.txt",
    "Justfile",
    "LICENSE",
    "README.md",
    "ROADMAP.md",
    "cache",
    "ci",
    "docs",
    "examples",
    "generated",
    "infra",
    "projects",
    "pyproject.toml",
    "pyrightconfig.json",
    "ruff.toml",
    "runtime",
    "schemas",
    "scripts",
    "sdk",
    "tests",
    "tools",
    "uv.lock",
    ".canary-bmt-pr-test-20260305",
}

FORBIDDEN_TRACKED_PREFIXES = (
    "debug/",
    "resources/",
)

FORBIDDEN_EXISTING_TOP_LEVEL = {
    "bmt",  # legacy core-main shell hook (removed; use projects/*/plugin.py)
    "debug",
    "resources",
}

_LEGACY_CLOUD_BMT_SUFFIX = "-cloud-bmt"

SUITE_REQUIRED_PATHS = (
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
    "Justfile",
    "pyproject.toml",
    "pyrightconfig.json",
    ".github/workflows",
    "cloud-ci-handoff",
    "projects",
    "examples",
    "projects/demo/project.bmt.json",
    "examples/project.bmt.json",
)

STANDALONE_REQUIRED_PATHS = (
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
    "Justfile",
    "pyproject.toml",
    "pyrightconfig.json",
    ".github/workflows",
    "projects",
    "examples",
    "projects/demo/project.bmt.json",
    "examples/project.bmt.json",
    "ci",
    "runtime",
    "sdk",
    "tests",
    "tools",
)

BACKEND_REQUIRED_PATHS = (
    ".github/actions/setup-bmt-pex/action.yml",
    DEFAULT_CONFIG_ROOT,
    "ci",
    "sdk",
    "tests",
    "tools",
    "tools/scripts/hooks/pre-commit-sync-gcp.sh",
)
# generated/stage (DEFAULT_STAGE_ROOT) is generated by materialization; not required in git.

SOURCE_VISIBILITY_REQUIRED_PATHS = (
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
    "docs/README.md",
    ".github/workflows/bmt-handoff.yml",
    ".github/workflows/build-and-test.yml",
    "cloud-ci-handoff/sdk/bmt_sdk/py.typed",
    "projects/demo/plugin.py",
    "projects/demo/project.bmt.json",
    "examples/plugin.py",
    "examples/project.bmt.json",
)

SOURCE_VISIBILITY_STANDALONE_PATHS = (
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
    "docs/README.md",
    ".github/workflows/bmt-handoff.yml",
    ".github/workflows/build-and-test.yml",
    "sdk/bmt_sdk/py.typed",
    "projects/demo/plugin.py",
    "projects/demo/project.bmt.json",
    "examples/plugin.py",
    "examples/project.bmt.json",
)


def _git_lines(args: list[str], *, cwd: Path) -> list[str]:
    proc = subprocess.run(
        ["git", "-c", f"safe.directory={cwd.as_posix()}", *args],
        check=False,
        capture_output=True,
        text=True,
        cwd=cwd,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {(proc.stderr or proc.stdout).strip()}")
    return [line.strip() for line in proc.stdout.splitlines() if line.strip()]


def _tracked_paths(root: Path) -> list[str]:
    prefix_proc = subprocess.run(
        ["git", "-c", f"safe.directory={root.as_posix()}", "rev-parse", "--show-prefix"],
        check=False,
        capture_output=True,
        text=True,
        cwd=root,
    )
    prefix = prefix_proc.stdout.strip() if prefix_proc.returncode == 0 else ""
    lines = _git_lines(["ls-files"], cwd=root) + _git_lines(["ls-files", "--others", "--exclude-standard"], cwd=root)
    paths: list[str] = []
    for line in lines:
        rel = line.strip()
        if not rel:
            continue
        if prefix:
            if not rel.startswith(prefix):
                continue
            rel = rel[len(prefix) :]
        if not (root / rel).exists():
            continue
        paths.append(rel)
    return sorted(set(paths))


def _ignored_paths(root: Path, paths: tuple[str, ...]) -> list[str]:
    proc = subprocess.run(
        ["git", "-c", f"safe.directory={root.as_posix()}", "check-ignore", "--no-index", "--stdin"],
        check=False,
        capture_output=True,
        input="\n".join(paths) + "\n",
        text=True,
        cwd=root,
    )
    if proc.returncode in (0, 1):
        return [line.strip() for line in proc.stdout.splitlines() if line.strip()]
    return []


def _rel_under(path: str, prefix: str) -> str | None:
    if path == prefix:
        return ""
    full_prefix = prefix.rstrip("/") + "/"
    if path.startswith(full_prefix):
        return path[len(full_prefix) :]
    return None


def _top_levels(paths: list[str], *, prefix: str = "") -> set[str]:
    names: set[str] = set()
    for path in paths:
        rel = _rel_under(path, prefix) if prefix else path
        if rel is None or not rel:
            continue
        names.add(rel.split("/", 1)[0])
    return names


def _load_json(path: Path) -> dict[str, object]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise RuntimeError(f"Could not read {path}: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Invalid JSON in {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise RuntimeError(f"Expected JSON object in {path}")
    return data


class RepoLayoutPolicy:
    """Validate suite and Cloud BMT backend repository layout policy."""

    def run(self) -> int:
        backend = repo_root()
        suite = suite_root()
        standalone = suite.resolve() == backend.resolve()
        tracked = _tracked_paths(suite)
        failures: list[str] = []

        suite_top_level = _top_levels(tracked)
        unexpected_suite = sorted(name for name in suite_top_level if name not in SUITE_ALLOWED_TOP_LEVEL)
        if unexpected_suite:
            failures.append("Unexpected suite top-level entries:")
            failures.extend([f"  - {name}" for name in unexpected_suite])

        legacy_roots = sorted(
            name for name in suite_top_level if name.endswith(_LEGACY_CLOUD_BMT_SUFFIX) or name == "template-cloud-bmt"
        )
        if legacy_roots:
            failures.append("Legacy *-cloud-bmt or template-cloud-bmt top-level folders are not allowed:")
            failures.extend([f"  - {name}" for name in legacy_roots])

        if standalone:
            unexpected_backend = sorted(name for name in suite_top_level if name not in BACKEND_ALLOWED_TOP_LEVEL)
            if unexpected_backend:
                failures.append("Unexpected repository top-level entries:")
                failures.extend([f"  - {name}" for name in unexpected_backend])
        else:
            backend_top_level = _top_levels(tracked, prefix=backend.name)
            unexpected_backend = sorted(name for name in backend_top_level if name not in BACKEND_ALLOWED_TOP_LEVEL)
            if unexpected_backend:
                failures.append("Unexpected cloud-ci-handoff top-level entries:")
                failures.extend([f"  - {backend.name}/{name}" for name in unexpected_backend])

        forbidden_tracked = sorted(
            path
            for path in tracked
            if path.startswith(FORBIDDEN_TRACKED_PREFIXES)
            and not path.startswith("projects/")
            and not path.startswith("examples/")
        )
        if forbidden_tracked:
            failures.append("Forbidden tracked prefixes found:")
            failures.extend([f"  - {path}" for path in forbidden_tracked[:30]])
            if len(forbidden_tracked) > 30:
                failures.append(f"  ... and {len(forbidden_tracked) - 30} more")

        required_suite_paths = STANDALONE_REQUIRED_PATHS if standalone else SUITE_REQUIRED_PATHS
        for rel in required_suite_paths:
            if not (suite / rel).exists():
                failures.append(f"Missing required suite path: {rel}")

        if not standalone:
            for rel in BACKEND_REQUIRED_PATHS:
                if not (backend / rel).exists():
                    failures.append(f"Missing required cloud-ci-handoff path: {backend.name}/{rel}")

        visibility_paths = SOURCE_VISIBILITY_STANDALONE_PATHS if standalone else SOURCE_VISIBILITY_REQUIRED_PATHS
        ignored_required = sorted(rel for rel in _ignored_paths(suite, visibility_paths) if (suite / rel).exists())
        if ignored_required:
            failures.append("Required source paths are ignored by Git:")
            failures.extend([f"  - {path}" for path in ignored_required])

        examples_manifest = examples_source_dir(suite) / "project.bmt.json"
        if examples_manifest.exists():
            examples_data = _load_json(examples_manifest)
            if examples_data.get("template") is not True:
                failures.append("examples/project.bmt.json must declare template=true")
            examples_deps = examples_data.get("python_dependencies", [])
            if not isinstance(examples_deps, list) or not all(
                isinstance(dep, str) and dep.strip() for dep in examples_deps
            ):
                failures.append("examples/project.bmt.json python_dependencies must be a list of non-empty strings")
            legacy_examples_json = sorted(
                path.name for path in examples_source_dir(suite).glob("*.json") if path.name != "project.bmt.json"
            )
            if legacy_examples_json:
                failures.append("examples/ must use project.bmt.json only for manifest scaffolding:")
                failures.extend([f"  - examples/{name}" for name in legacy_examples_json])

        try:
            project_dirs = discover_project_sources(suite)
        except (FileNotFoundError, ValueError) as exc:
            failures.append(str(exc))
            project_dirs = []

        for project_dir in project_dirs:
            data = load_project_manifest(project_dir)
            if data.get("template") is True:
                failures.append(f"Deployable project must not declare template=true: {project_dir}")
            deps = data.get("python_dependencies", [])
            if not isinstance(deps, list) or not all(isinstance(dep, str) and dep.strip() for dep in deps):
                failures.append(f"python_dependencies must be a list of non-empty strings: {project_dir.name}")
            allowed_project_json = {"project.bmt.json"}
            legacy_json = sorted(
                path.name for path in project_dir.glob("*.json") if path.name not in allowed_project_json
            )
            if legacy_json:
                failures.append(f"Project source must use project.bmt.json only for BMT manifests: {project_dir.name}")
                failures.extend([f"  - {project_dir.name}/{name}" for name in legacy_json])
            if (project_dir / "pyproject.toml").exists():
                failures.append(f"Project-local pyproject.toml is not allowed by default: {project_dir.name}")

        generated_prefix = (
            f"{DEFAULT_STAGE_ROOT.as_posix().rstrip('/')}/"
            if standalone
            else f"{backend.name}/{DEFAULT_STAGE_ROOT.as_posix().rstrip('/')}/"
        )
        generated_tracked = sorted(path for path in tracked if path.startswith(generated_prefix))
        if generated_tracked:
            failures.append("Generated stage output must not be tracked:")
            failures.extend([f"  - {path}" for path in generated_tracked[:30]])
            if len(generated_tracked) > 30:
                failures.append(f"  ... and {len(generated_tracked) - 30} more")

        forbidden_existing = sorted(name for name in FORBIDDEN_EXISTING_TOP_LEVEL if (suite / name).exists())
        if forbidden_existing:
            failures.append("Forbidden top-level local directories exist:")
            failures.extend([f"  - {name}" for name in forbidden_existing])

        if failures:
            for line in failures:
                print(f"::error::{line}", file=sys.stderr)
            return 1

        print("Repository layout policy check passed")
        print("Suite and cloud-ci-handoff top-level entries are within policy.")
        print("Project examples tree, generated stage, and legacy plugin paths are guarded.")
        return 0


if __name__ == "__main__":
    raise SystemExit(RepoLayoutPolicy().run())
